// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: pkg/proto/messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encoding int32

const (
	Encoding_RAW  Encoding = 0
	Encoding_LZ4  Encoding = 1
	Encoding_ZSTD Encoding = 2
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "RAW",
		1: "LZ4",
		2: "ZSTD",
	}
	Encoding_value = map[string]int32{
		"RAW":  0,
		"LZ4":  1,
		"ZSTD": 2,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_messages_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_pkg_proto_messages_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_PENDING TaskStatus = 0
	TaskStatus_RUNNING TaskStatus = 1
	TaskStatus_SUCCESS TaskStatus = 2
	TaskStatus_FAILED  TaskStatus = 3
	TaskStatus_TIMEOUT TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "SUCCESS",
		3: "FAILED",
		4: "TIMEOUT",
	}
	TaskStatus_value = map[string]int32{
		"PENDING": 0,
		"RUNNING": 1,
		"SUCCESS": 2,
		"FAILED":  3,
		"TIMEOUT": 4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_messages_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_messages_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{1}
}

type PageResponse_Status int32

const (
	PageResponse_OK               PageResponse_Status = 0
	PageResponse_NOT_FOUND        PageResponse_Status = 1
	PageResponse_VERSION_MISMATCH PageResponse_Status = 2
)

// Enum value maps for PageResponse_Status.
var (
	PageResponse_Status_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "VERSION_MISMATCH",
	}
	PageResponse_Status_value = map[string]int32{
		"OK":               0,
		"NOT_FOUND":        1,
		"VERSION_MISMATCH": 2,
	}
)

func (x PageResponse_Status) Enum() *PageResponse_Status {
	p := new(PageResponse_Status)
	*p = x
	return p
}

func (x PageResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PageResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_messages_proto_enumTypes[2].Descriptor()
}

func (PageResponse_Status) Type() protoreflect.EnumType {
	return &file_pkg_proto_messages_proto_enumTypes[2]
}

func (x PageResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PageResponse_Status.Descriptor instead.
func (PageResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{7, 0}
}

type LeaseRequest_Kind int32

const (
	LeaseRequest_READ  LeaseRequest_Kind = 0
	LeaseRequest_WRITE LeaseRequest_Kind = 1
)

// Enum value maps for LeaseRequest_Kind.
var (
	LeaseRequest_Kind_name = map[int32]string{
		0: "READ",
		1: "WRITE",
	}
	LeaseRequest_Kind_value = map[string]int32{
		"READ":  0,
		"WRITE": 1,
	}
)

func (x LeaseRequest_Kind) Enum() *LeaseRequest_Kind {
	p := new(LeaseRequest_Kind)
	*p = x
	return p
}

func (x LeaseRequest_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseRequest_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_messages_proto_enumTypes[3].Descriptor()
}

func (LeaseRequest_Kind) Type() protoreflect.EnumType {
	return &file_pkg_proto_messages_proto_enumTypes[3]
}

func (x LeaseRequest_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseRequest_Kind.Descriptor instead.
func (LeaseRequest_Kind) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{8, 0}
}

// Control plane messages
type ControlHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Caps          *NodeCapabilities      `protobuf:"bytes,2,opt,name=caps,proto3" json:"caps,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	PqPubkey      []byte                 `protobuf:"bytes,4,opt,name=pq_pubkey,json=pqPubkey,proto3" json:"pq_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlHello) Reset() {
	*x = ControlHello{}
	mi := &file_pkg_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlHello) ProtoMessage() {}

func (x *ControlHello) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlHello.ProtoReflect.Descriptor instead.
func (*ControlHello) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ControlHello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ControlHello) GetCaps() *NodeCapabilities {
	if x != nil {
		return x.Caps
	}
	return nil
}

func (x *ControlHello) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *ControlHello) GetPqPubkey() []byte {
	if x != nil {
		return x.PqPubkey
	}
	return nil
}

type NodeCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	HasGpu        bool                   `protobuf:"varint,3,opt,name=has_gpu,json=hasGpu,proto3" json:"has_gpu,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_pkg_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *NodeCapabilities) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeCapabilities) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *NodeCapabilities) GetHasGpu() bool {
	if x != nil {
		return x.HasGpu
	}
	return false
}

func (x *NodeCapabilities) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ClusterState struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	RaftTerm         uint64                      `protobuf:"varint,1,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	Rings            map[string]*Ring            `protobuf:"bytes,2,rep,name=rings,proto3" json:"rings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShardAssignments map[string]*ShardAssignment `protobuf:"bytes,3,rep,name=shard_assignments,json=shardAssignments,proto3" json:"shard_assignments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Epoch            uint64                      `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClusterState) Reset() {
	*x = ClusterState{}
	mi := &file_pkg_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterState) ProtoMessage() {}

func (x *ClusterState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterState.ProtoReflect.Descriptor instead.
func (*ClusterState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterState) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

func (x *ClusterState) GetRings() map[string]*Ring {
	if x != nil {
		return x.Rings
	}
	return nil
}

func (x *ClusterState) GetShardAssignments() map[string]*ShardAssignment {
	if x != nil {
		return x.ShardAssignments
	}
	return nil
}

func (x *ClusterState) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type Ring struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceClass string                 `protobuf:"bytes,1,opt,name=resource_class,json=resourceClass,proto3" json:"resource_class,omitempty"`
	Nodes         []*RingNode            `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ring) Reset() {
	*x = Ring{}
	mi := &file_pkg_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ring) ProtoMessage() {}

func (x *Ring) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ring.ProtoReflect.Descriptor instead.
func (*Ring) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Ring) GetResourceClass() string {
	if x != nil {
		return x.ResourceClass
	}
	return ""
}

func (x *Ring) GetNodes() []*RingNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type RingNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RingNode) Reset() {
	*x = RingNode{}
	mi := &file_pkg_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingNode) ProtoMessage() {}

func (x *RingNode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingNode.ProtoReflect.Descriptor instead.
func (*RingNode) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RingNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RingNode) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ShardAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArrayId       string                 `protobuf:"bytes,1,opt,name=array_id,json=arrayId,proto3" json:"array_id,omitempty"`
	PageId        int32                  `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	OwnerNodeId   string                 `protobuf:"bytes,3,opt,name=owner_node_id,json=ownerNodeId,proto3" json:"owner_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardAssignment) Reset() {
	*x = ShardAssignment{}
	mi := &file_pkg_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAssignment) ProtoMessage() {}

func (x *ShardAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAssignment.ProtoReflect.Descriptor instead.
func (*ShardAssignment) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ShardAssignment) GetArrayId() string {
	if x != nil {
		return x.ArrayId
	}
	return ""
}

func (x *ShardAssignment) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ShardAssignment) GetOwnerNodeId() string {
	if x != nil {
		return x.OwnerNodeId
	}
	return ""
}

// Data plane messages
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArrayId       string                 `protobuf:"bytes,1,opt,name=array_id,json=arrayId,proto3" json:"array_id,omitempty"`
	PageId        int32                  `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	WantVersion   int64                  `protobuf:"varint,3,opt,name=want_version,json=wantVersion,proto3" json:"want_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_pkg_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *PageRequest) GetArrayId() string {
	if x != nil {
		return x.ArrayId
	}
	return ""
}

func (x *PageRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *PageRequest) GetWantVersion() int64 {
	if x != nil {
		return x.WantVersion
	}
	return 0
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PageResponse_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=holocompute.proto.PageResponse_Status" json:"status,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Checksum      []byte                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Encoding      Encoding               `protobuf:"varint,4,opt,name=encoding,proto3,enum=holocompute.proto.Encoding" json:"encoding,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_pkg_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *PageResponse) GetStatus() PageResponse_Status {
	if x != nil {
		return x.Status
	}
	return PageResponse_OK
}

func (x *PageResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PageResponse) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *PageResponse) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_RAW
}

func (x *PageResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type LeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArrayId       string                 `protobuf:"bytes,1,opt,name=array_id,json=arrayId,proto3" json:"array_id,omitempty"`
	PageId        int32                  `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Kind          LeaseRequest_Kind      `protobuf:"varint,3,opt,name=kind,proto3,enum=holocompute.proto.LeaseRequest_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_pkg_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *LeaseRequest) GetArrayId() string {
	if x != nil {
		return x.ArrayId
	}
	return ""
}

func (x *LeaseRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *LeaseRequest) GetKind() LeaseRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return LeaseRequest_READ
}

type LeaseGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	TtlMs         int64                  `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseGrant) Reset() {
	*x = LeaseGrant{}
	mi := &file_pkg_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrant) ProtoMessage() {}

func (x *LeaseGrant) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrant.ProtoReflect.Descriptor instead.
func (*LeaseGrant) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *LeaseGrant) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseGrant) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type TaskSubmit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WasmModSha    []byte                 `protobuf:"bytes,2,opt,name=wasm_mod_sha,json=wasmModSha,proto3" json:"wasm_mod_sha,omitempty"`
	InputsRef     map[string]string      `protobuf:"bytes,3,rep,name=inputs_ref,json=inputsRef,proto3" json:"inputs_ref,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceHints *ResourceHints         `protobuf:"bytes,4,opt,name=resource_hints,json=resourceHints,proto3" json:"resource_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSubmit) Reset() {
	*x = TaskSubmit{}
	mi := &file_pkg_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSubmit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSubmit) ProtoMessage() {}

func (x *TaskSubmit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSubmit.ProtoReflect.Descriptor instead.
func (*TaskSubmit) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{10}
}

func (x *TaskSubmit) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskSubmit) GetWasmModSha() []byte {
	if x != nil {
		return x.WasmModSha
	}
	return nil
}

func (x *TaskSubmit) GetInputsRef() map[string]string {
	if x != nil {
		return x.InputsRef
	}
	return nil
}

func (x *TaskSubmit) GetResourceHints() *ResourceHints {
	if x != nil {
		return x.ResourceHints
	}
	return nil
}

type ResourceHints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int32                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu           bool                   `protobuf:"varint,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceHints) Reset() {
	*x = ResourceHints{}
	mi := &file_pkg_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceHints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceHints) ProtoMessage() {}

func (x *ResourceHints) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceHints.ProtoReflect.Descriptor instead.
func (*ResourceHints) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceHints) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceHints) GetGpu() bool {
	if x != nil {
		return x.Gpu
	}
	return false
}

func (x *ResourceHints) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=holocompute.proto.TaskStatus" json:"status,omitempty"`
	OutputsRef    map[string]string      `protobuf:"bytes,3,rep,name=outputs_ref,json=outputsRef,proto3" json:"outputs_ref,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Logs          string                 `protobuf:"bytes,4,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_pkg_proto_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_pkg_proto_messages_proto_rawDescGZIP(), []int{12}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_PENDING
}

func (x *TaskResult) GetOutputsRef() map[string]string {
	if x != nil {
		return x.OutputsRef
	}
	return nil
}

func (x *TaskResult) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_pkg_proto_messages_proto protoreflect.FileDescriptor

const file_pkg_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/messages.proto\x12\x11holocompute.proto\"\x95\x01\n" +
	"\fControlHello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x127\n" +
	"\x04caps\x18\x02 \x01(\v2#.holocompute.proto.NodeCapabilitiesR\x04caps\x12\x16\n" +
	"\x06pubkey\x18\x03 \x01(\fR\x06pubkey\x12\x1b\n" +
	"\tpq_pubkey\x18\x04 \x01(\fR\bpqPubkey\"\x7f\n" +
	"\x10NodeCapabilities\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x17\n" +
	"\ahas_gpu\x18\x03 \x01(\bR\x06hasGpu\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\xa3\x03\n" +
	"\fClusterState\x12\x1b\n" +
	"\traft_term\x18\x01 \x01(\x04R\braftTerm\x12@\n" +
	"\x05rings\x18\x02 \x03(\v2*.holocompute.proto.ClusterState.RingsEntryR\x05rings\x12b\n" +
	"\x11shard_assignments\x18\x03 \x03(\v25.holocompute.proto.ClusterState.ShardAssignmentsEntryR\x10shardAssignments\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x04R\x05epoch\x1aQ\n" +
	"\n" +
	"RingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.holocompute.proto.RingR\x05value:\x028\x01\x1ag\n" +
	"\x15ShardAssignmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".holocompute.proto.ShardAssignmentR\x05value:\x028\x01\"`\n" +
	"\x04Ring\x12%\n" +
	"\x0eresource_class\x18\x01 \x01(\tR\rresourceClass\x121\n" +
	"\x05nodes\x18\x02 \x03(\v2\x1b.holocompute.proto.RingNodeR\x05nodes\";\n" +
	"\bRingNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\"i\n" +
	"\x0fShardAssignment\x12\x19\n" +
	"\barray_id\x18\x01 \x01(\tR\aarrayId\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\x05R\x06pageId\x12\"\n" +
	"\rowner_node_id\x18\x03 \x01(\tR\vownerNodeId\"d\n" +
	"\vPageRequest\x12\x19\n" +
	"\barray_id\x18\x01 \x01(\tR\aarrayId\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\x05R\x06pageId\x12!\n" +
	"\fwant_version\x18\x03 \x01(\x03R\vwantVersion\"\x8e\x02\n" +
	"\fPageResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.holocompute.proto.PageResponse.StatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\fR\bchecksum\x127\n" +
	"\bencoding\x18\x04 \x01(\x0e2\x1b.holocompute.proto.EncodingR\bencoding\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"5\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x14\n" +
	"\x10VERSION_MISMATCH\x10\x02\"\x99\x01\n" +
	"\fLeaseRequest\x12\x19\n" +
	"\barray_id\x18\x01 \x01(\tR\aarrayId\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\x05R\x06pageId\x128\n" +
	"\x04kind\x18\x03 \x01(\x0e2$.holocompute.proto.LeaseRequest.KindR\x04kind\"\x1b\n" +
	"\x04Kind\x12\b\n" +
	"\x04READ\x10\x00\x12\t\n" +
	"\x05WRITE\x10\x01\">\n" +
	"\n" +
	"LeaseGrant\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x03R\x05ttlMs\"\x9b\x02\n" +
	"\n" +
	"TaskSubmit\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12 \n" +
	"\fwasm_mod_sha\x18\x02 \x01(\fR\n" +
	"wasmModSha\x12K\n" +
	"\n" +
	"inputs_ref\x18\x03 \x03(\v2,.holocompute.proto.TaskSubmit.InputsRefEntryR\tinputsRef\x12G\n" +
	"\x0eresource_hints\x18\x04 \x01(\v2 .holocompute.proto.ResourceHintsR\rresourceHints\x1a<\n" +
	"\x0eInputsRefEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\rResourceHints\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x05R\x03cpu\x12\x10\n" +
	"\x03gpu\x18\x02 \x01(\bR\x03gpu\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x05R\bmemoryMb\"\xff\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.holocompute.proto.TaskStatusR\x06status\x12N\n" +
	"\voutputs_ref\x18\x03 \x03(\v2-.holocompute.proto.TaskResult.OutputsRefEntryR\n" +
	"outputsRef\x12\x12\n" +
	"\x04logs\x18\x04 \x01(\tR\x04logs\x1a=\n" +
	"\x0fOutputsRefEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*&\n" +
	"\bEncoding\x12\a\n" +
	"\x03RAW\x10\x00\x12\a\n" +
	"\x03LZ4\x10\x01\x12\b\n" +
	"\x04ZSTD\x10\x02*L\n" +
	"\n" +
	"TaskStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04B*Z(github.com/melihxz/holocompute/pkg/protob\x06proto3"

var (
	file_pkg_proto_messages_proto_rawDescOnce sync.Once
	file_pkg_proto_messages_proto_rawDescData []byte
)

func file_pkg_proto_messages_proto_rawDescGZIP() []byte {
	file_pkg_proto_messages_proto_rawDescOnce.Do(func() {
		file_pkg_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_messages_proto_rawDesc), len(file_pkg_proto_messages_proto_rawDesc)))
	})
	return file_pkg_proto_messages_proto_rawDescData
}

var file_pkg_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pkg_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_proto_messages_proto_goTypes = []any{
	(Encoding)(0),            // 0: holocompute.proto.Encoding
	(TaskStatus)(0),          // 1: holocompute.proto.TaskStatus
	(PageResponse_Status)(0), // 2: holocompute.proto.PageResponse.Status
	(LeaseRequest_Kind)(0),   // 3: holocompute.proto.LeaseRequest.Kind
	(*ControlHello)(nil),     // 4: holocompute.proto.ControlHello
	(*NodeCapabilities)(nil), // 5: holocompute.proto.NodeCapabilities
	(*ClusterState)(nil),     // 6: holocompute.proto.ClusterState
	(*Ring)(nil),             // 7: holocompute.proto.Ring
	(*RingNode)(nil),         // 8: holocompute.proto.RingNode
	(*ShardAssignment)(nil),  // 9: holocompute.proto.ShardAssignment
	(*PageRequest)(nil),      // 10: holocompute.proto.PageRequest
	(*PageResponse)(nil),     // 11: holocompute.proto.PageResponse
	(*LeaseRequest)(nil),     // 12: holocompute.proto.LeaseRequest
	(*LeaseGrant)(nil),       // 13: holocompute.proto.LeaseGrant
	(*TaskSubmit)(nil),       // 14: holocompute.proto.TaskSubmit
	(*ResourceHints)(nil),    // 15: holocompute.proto.ResourceHints
	(*TaskResult)(nil),       // 16: holocompute.proto.TaskResult
	nil,                      // 17: holocompute.proto.ClusterState.RingsEntry
	nil,                      // 18: holocompute.proto.ClusterState.ShardAssignmentsEntry
	nil,                      // 19: holocompute.proto.TaskSubmit.InputsRefEntry
	nil,                      // 20: holocompute.proto.TaskResult.OutputsRefEntry
}
var file_pkg_proto_messages_proto_depIdxs = []int32{
	5,  // 0: holocompute.proto.ControlHello.caps:type_name -> holocompute.proto.NodeCapabilities
	17, // 1: holocompute.proto.ClusterState.rings:type_name -> holocompute.proto.ClusterState.RingsEntry
	18, // 2: holocompute.proto.ClusterState.shard_assignments:type_name -> holocompute.proto.ClusterState.ShardAssignmentsEntry
	8,  // 3: holocompute.proto.Ring.nodes:type_name -> holocompute.proto.RingNode
	2,  // 4: holocompute.proto.PageResponse.status:type_name -> holocompute.proto.PageResponse.Status
	0,  // 5: holocompute.proto.PageResponse.encoding:type_name -> holocompute.proto.Encoding
	3,  // 6: holocompute.proto.LeaseRequest.kind:type_name -> holocompute.proto.LeaseRequest.Kind
	19, // 7: holocompute.proto.TaskSubmit.inputs_ref:type_name -> holocompute.proto.TaskSubmit.InputsRefEntry
	15, // 8: holocompute.proto.TaskSubmit.resource_hints:type_name -> holocompute.proto.ResourceHints
	1,  // 9: holocompute.proto.TaskResult.status:type_name -> holocompute.proto.TaskStatus
	20, // 10: holocompute.proto.TaskResult.outputs_ref:type_name -> holocompute.proto.TaskResult.OutputsRefEntry
	7,  // 11: holocompute.proto.ClusterState.RingsEntry.value:type_name -> holocompute.proto.Ring
	9,  // 12: holocompute.proto.ClusterState.ShardAssignmentsEntry.value:type_name -> holocompute.proto.ShardAssignment
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_proto_messages_proto_init() }
func file_pkg_proto_messages_proto_init() {
	if File_pkg_proto_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_messages_proto_rawDesc), len(file_pkg_proto_messages_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_messages_proto_goTypes,
		DependencyIndexes: file_pkg_proto_messages_proto_depIdxs,
		EnumInfos:         file_pkg_proto_messages_proto_enumTypes,
		MessageInfos:      file_pkg_proto_messages_proto_msgTypes,
	}.Build()
	File_pkg_proto_messages_proto = out.File
	file_pkg_proto_messages_proto_goTypes = nil
	file_pkg_proto_messages_proto_depIdxs = nil
}
